#!/usr/bin/env bash
#
# Copyright 2025 8dcc. All Rights Reserved.
#
# This file is part of bitdump.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <https://www.gnu.org/licenses/>.
set -e

BITDUMP='bitdump'
DIFF='diff'

if [ $# -ne 2 ]; then
    echo "Usage: $(basename "$0") BIN1 BIN2" 1>&2
    return 1
fi

assert_cmd() {
    if [ ! "$(command -v "$1")" ]; then
        echo "$(basename "$0"): The '$1' command is not installed." 1>&2
        exit 1
    fi
}

assert_cmd "$BITDUMP"
assert_cmd "$DIFF"

# Use bash's Process Substitution to send the output of the two 'bitdump'
# commands to 'diff'. See:
# https://www.gnu.org/software/bash/manual/html_node/Process-Substitution.html
$DIFF <($BITDUMP "$1") <($BITDUMP "$2")
